version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.1-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - MONGODB_INITDB_DATABASE=subscription
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/data/db
