spring:
  data:
    mongodb:
      auto-index-creation: true
      database: ${MONGO_DB:subscription}
      password: ${MONGO_PASS:pass}
      username: ${MONGO_USER:user}
      authentication-database: admin
