cloud:
  aws:
    credentials:
      access-key: ${SES_USER:}
      secret-key: ${SES_PASS:}
    region:
      static: ${SES_REGION:eu-central-1}
email:
  default-sender: ${EMAIL:}
  max-errors: ${MAX_ERRORS:3}
security:
  cors:
    origin-url: ${CORS_ORIGIN:http://localhost:3000}
spring:
  data:
    mongodb:
      auto-index-creation: true
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:subscription}
      password: ${MONGO_PASS:pass}
      username: ${MONGO_USER:user}
      authentication-database: admin
