cloud:
  aws:
    credentials:
      access-key: ${SES_USER:}
      secret-key: ${SES_PASS:}
    region:
      static: ${SES_REGION:eu-central-1}
email:
  default-sender: ${EMAIL:}
  max-errors: ${MAX_ERRORS:3}
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: ${MONGO_DB:subscription}
      password: ${MONGO_PASS:pass}
      username: ${MONGO_USER:user}
      authentication-database: admin
